name: action-date test
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: ajilraju/actions-date@v0.0.2
        with:
          args: date +%F
      - name: echo date test
        env:
          JOB_START: $${{ date "+%Y-%m-%d-%H:%M" }}
        run: |
          echo "today's date: $(date +%d-%m-%Y)"
